//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestCarritoPi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carrito()
        {
            this.preventa = new HashSet<preventa>();
        }
    
        public string car_cod_carro { get; set; }
        public string car_tipo_carro { get; set; }
        public string car_user_crea { get; set; }
        public Nullable<System.DateTime> car_fecha_crea { get; set; }
        public string car_user_mod { get; set; }
        public Nullable<System.DateTime> car_fecha_mod { get; set; }
        public Nullable<int> car_estado_carro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<preventa> preventa { get; set; }
    }
}
