//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestCarritoPi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nps
    {
        public string idNps { get; set; }
        public Nullable<decimal> ScorePregunta { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> fechaNps { get; set; }
        public Nullable<int> estadoNps { get; set; }
    }
}
