//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestCarritoPi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class preventa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public preventa()
        {
            this.detalle_preventa = new HashSet<detalle_preventa>();
        }
    
        public string pre_cod_preventa { get; set; }
        public string cli_nit_cliente { get; set; }
        public string car_cod_carro { get; set; }
        public Nullable<System.DateTime> pre_fecha_venta { get; set; }
        public Nullable<decimal> pre_precio_total { get; set; }
        public Nullable<int> pre_estado_venta { get; set; }
    
        public virtual carrito carrito { get; set; }
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_preventa> detalle_preventa { get; set; }
    }
}
