//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestCarritoPi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.detalle_preventa = new HashSet<detalle_preventa>();
        }
    
        public string pro_correlativo { get; set; }
        public string pro_nombre { get; set; }
        public string pro_descripcion { get; set; }
        public Nullable<int> pro_stock { get; set; }
        public string pro_tipo_paquete { get; set; }
        public Nullable<decimal> pro_peso { get; set; }
        public Nullable<decimal> pro_precio_venta { get; set; }
        public Nullable<decimal> pro_precio_compra { get; set; }
        public Nullable<decimal> pro_descuento_prod { get; set; }
        public string pro_user_crea { get; set; }
        public Nullable<System.DateTime> pro_fecha_crea { get; set; }
        public string pro_user_mod { get; set; }
        public Nullable<System.DateTime> pro_fecha_mod { get; set; }
        public Nullable<int> pro_estado { get; set; }
        public byte[] pro_image_producto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_preventa> detalle_preventa { get; set; }
    }
}
